# @author Laurent Krishnathas
# @year 2018
version: '3.5'

services:
  traefik:
    deploy:
      resources:
        limits:
          memory: ${MEM_10_PCT}

  browser:
    volumes:
      - /efs/config/browser:/config:z
    deploy:
      resources:
        limits:
          memory: ${MEM_40_PCT}

  bioregister:
    volumes:
      - /efs/config/browser:/config:z
    deploy:
      resources:
        limits:
          memory: ${MEM_40_PCT}
