# @author Laurent Krishnathas
# @year 2018
version: '3.5'

services:
  traefik:
    deploy:
      resources:
        limits:
          memory: ${TRAEFIK_LIMIT_MEM}

  browser:
    volumes:
      - /efs/config/browser:/config:z
    deploy:
      resources:
        limits:
          memory: ${BROWSER_LIMIT_MEM}

  bioregister:
    volumes:
      - /efs/config/browser:/config:z
    deploy:
      resources:
        limits:
          memory: ${BIOREGISTER_LIMIT_MEM}
