project:
  name: quickstart-dotmatics
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - eu-west-1
  - us-east-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-biotech-blueprintt1:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-dotmatics/
      pAsmPass: Test1234#
      pAvailabilityZones: $[taskcat_genaz_2]
      pDataGuardConfig: Single
      pDatabasePass: Test1234#
      pEC2KeyPair: sshvans
      pInstallBucketName: devspacepaul
      pInstallBucketPrefix: oraclebins
      pOracleInstanceType: t2.large
      pPrimaryIPAddress: 10.80.32.5
      pPrivateSubnet1CIDR: 10.80.32.0/20
      pPrivateSubnet2CIDR: 10.80.48.0/20
      pPublicSubnet1CIDR: 10.80.0.0/20
      pPublicSubnet2CIDR: 10.80.16.0/20
      pStandbyIPAddress: 10.80.48.5
      pVPCCIDR: 10.80.0.0/16
      pWebAccessCIDR: 0.0.0.0/0
    regions:
    - eu-west-1
    s3_bucket: ''
    template: templates/dotmatics-master.template
