global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-dotmatics
  s3bucket: quickstart-test-dotmatics-devops-v2
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
  reporting: true
tests:
  quickstart-biotech-blueprintt1:
    parameter_input: dotmatics-params.t1.json
    template_file: dotmatics-master.template
    regions:
      - eu-west-1
